### ISSUE TITLE
Can provide Chinese version by redis.io ?

### ISSUE THREAD

**Issue by WiFeng** [antirez/redis-io#142]
We can help to translation all pages

**Comment by antirez** [comment]
Hello @WiFeng, I'm involved in open source for 20 years and more at this point, and I do not believe translations of web pages are the way to go... I'm Italian so I can understand how hard is learning English but it's the only path. I'm having recently the great pleasure of collaborating with some great Chinese developer such as @soloestoy, and this is only possible because we can both talk in English... So I believe that translations are not a good idea and it's better if people learn some English. Cheers!

**Comment by WiFeng** [comment]
Ok , Cheers!
